# Generated by Django 4.0 on 2022-01-14 12:05

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', "0005_remove_userfollows_can't follow yourself_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userfollows',
            name="can't follow yourself",
        ),
        migrations.AddConstraint(
            model_name='userfollows',
            constraint=models.CheckConstraint(check=models.Q(('user', django.db.models.expressions.F('user')), _negated=True), name='no follow yourself'),
        ),
    ]
